Models/Flock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NikeFarms.v2._0.Models
{
    public class Flock : BaseEntity
    {

        public FlockType FlockType { get; set; }

        public int FlockTypeId { get; set; }

        public string BatchNo { get; set; }

        public int TotalNo { get; set; }

        public int Age { get; set; }

        public double AverageWeight { get; set; }

        public decimal AmountPurchased { get; set; }

        public bool IsApproved { get; set; }

        public int AvailableBirds { get; set; } 


        List<DailyActivity> DailyActivities { get; set; }

        List<Stock> Stocks { get; set; }
    }
}

Models/FlockType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NikeFarms.v2._0.Models
{
    public class FlockType : BaseEntity
    {
        public string Name { get; set; }

        public string Description { get; set; }

        List<Flock> Flocks { get; set; }
    }
}

Controllers/FlockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NikeFarms.v2._0.Interface;
using NikeFarms.v2._0.Models;
using NikeFarms.v2._0.Models.DTO;
using NikeFarms.v2._0.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NikeFarms.v2._0.Controllers
{
    
    public class FlockController : Controller
    {
        private readonly IUserService _userService;
        private readonly IFlockService _flockService;
        private readonly IWeeklyReportService _weeklyReportService;
        private readonly IFlockTypeService _flockTypeService;
        private readonly ISalesItemService _salesItemService;
        private readonly IUserRoleService _userRoleService;
        private readonly IRoleService _roleService;
        private readonly INotificationService _notificationService;

        public FlockController(IUserService userService, IFlockService flockService, IFlockTypeService flockTypeService, IUserRoleService userRoleService, INotificationService notificationService, IRoleService roleService, IWeeklyReportService weeklyReportService, ISalesItemService salesItemService)
        {
            _userService = userService;
            _flockService = flockService;
            _flockTypeService = flockTypeService;
            _userRoleService = userRoleService;
            _notificationService = notificationService;
            _roleService = roleService;
            _weeklyReportService = weeklyReportService;
            _salesItemService = salesItemService;
        }

        [Authorize(Roles = "Super Admin, Store Manager")]
        public IActionResult Index(string sortOrder, string searchString, int? pageNumber)
        {
            var flocks = _flockService.GetAllFlocks();
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                flocks = flocks.Where(s => s.BatchNo.Contains(searchString)|| s.FlockType.Name.Contains(searchString));
            }
            List<ListFlockVM> ListFlock = new List<ListFlockVM>();
            foreach (var flock in flocks.ToList())
            {
                var Created = _userService.FindByEmail(flock.CreatedBy);

                ListFlockVM listFlockVM = new ListFlockVM
                {
                    Id = flock.Id,
                    BatchNo = flock.BatchNo,
                    FlockType = _flockTypeService.FindById(flock.FlockTypeId).Name,
                    currentAge = (int)((DateTime.Now - flock.CreatedAt).TotalDays) + flock.Age,
                    TotalNo = flock.TotalNo,
                    AvailableBirds = flock.AvailableBirds,
                    CurrentAverageWeight = _flockService.GetCurrentAverageWeight(flock.Id),
                    Mortality = _flockService.Mortality(flock.Id),
                    IsApproved = flock.IsApproved,
                    CreatedBy = $"{Created.FirstName} .{Created.LastName[0]}",
                };

                ListFlock.Add(listFlockVM);
            }

            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            User userlogin = _userService.FindById(userId);
            ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";
            int pageSize = 5;
            return View(PaginatedList<ListFlockVM>.CreateAsync(ListFlock.AsQueryable(), pageNumber ?? 1, pageSize));
        }

        [Authorize(Roles = "Super Admin, Store Manager")]
        public IActionResult AddFlock()
        {
            AddFlockVM flockVM = new AddFlockVM
            {
                FlockTypeList = _flockTypeService.GetAllFlockTypes().Select(m => new SelectListItem
                {
                    Text = m.Name,
                    Value = m.Id.ToString()
                })
            };

            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            User userlogin = _userService.FindById(userId);
            ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";

            return View(flockVM);
        }

        [HttpPost]
        public IActionResult AddFlock(AddFlockVM addFlock)
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            
            FlockDTO flockDTO = new FlockDTO
            {
                UserId = userId,
                TotalNo = addFlock.TotalNo,
                Age = addFlock.Age,
                AverageWeight = addFlock.AverageWeight,
                AvailableBird = addFlock.TotalNo,
                FlockTypeId = addFlock.FlockTypeId,
                AmountPurchased = addFlock.AmountPurchased,
                IsApproved = false,
            };

            _flockService.Add(flockDTO);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Super Admin, Store Manager")]
        public IActionResult UpdateFlock(int id)
        {
            var flock = _flockService.FindById(id);
            if (flock == null || flock.IsApproved == true)
            {
                return NotFound();
            }
            else
            {
                int userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
                User userlogin = _userService.FindById(userId);
                ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";

                UpdateFlockVM updateFlock = new UpdateFlockVM
                {
                    Id = flock.Id,
                    TotalNo = flock.TotalNo,
                    AverageWeight = flock.AverageWeight,
                    Age = flock.Age,
                    AmountPurchased = flock.AmountPurchased,
                    FlockTypeId = flock.FlockTypeId,
                    FlockTypeList = _flockTypeService.GetAllFlockTypes().Select(m => new SelectListItem
                    {
                        Text = m.Name,
                        Value = m.Id.ToString(),
                    }),
                };

                return View(updateFlock);
            }

        }

        [HttpPost]
        public IActionResult UpdateFlock(UpdateFlockVM updateFlock)
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = _userService.FindById(userId);

            FlockDTO flock = new FlockDTO
            {
                UserId = userId,
                Id = updateFlock.Id,
                TotalNo = updateFlock.TotalNo,
                AverageWeight = updateFlock.AverageWeight,
                Age = updateFlock.Age,
                AvailableBird = updateFlock.TotalNo,
                AmountPurchased = updateFlock.AmountPurchased,
                FlockTypeId = updateFlock.FlockTypeId,
                IsApproved = false,
            };
            _flockService.Update(flock);
            
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Super Admin, Store Manager")]
        public IActionResult Delete(int id)
        {
            var flock = _flockService.FindById(id);
            if (flock == null || flock.IsApproved == true)
            {
                return NotFound();
            }
            _flockService.Delete(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Super Admin, Admin")]
        public IActionResult ListApprovedFlock(string sortOrder, int? pageNumber)
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var flocks = _flockService.GetApprovedFlocks();
            ViewData["CurrentSort"] = sortOrder; 
            List<ListFlockVM> ListFlock = new List<ListFlockVM>();
            foreach (var flock in flocks)
            {
                var Created = _userService.FindByEmail(flock.CreatedBy);

                ListFlockVM listFlockVM = new ListFlockVM
                {
                    Id = flock.Id,
                    BatchNo = flock.BatchNo,
                    FlockType = _flockTypeService.FindById(flock.FlockTypeId).Name,
                    currentAge = (int)((DateTime.Now - flock.CreatedAt).TotalDays) + flock.Age,
                    TotalNo = flock.TotalNo,
                    AvailableBirds = flock.AvailableBirds,
                    InitialAverageWeight = flock.AverageWeight,
                    CurrentAverageWeight = _flockService.GetCurrentAverageWeight(flock.Id),
                    IsApproved = flock.IsApproved,
                    Mortality = _flockService.Mortality(flock.Id),
                    CreatedBy = $"{Created.FirstName} .{Created.LastName[0]}",
                    PriceSpentOnFeed = _flockService.GetAmountSpentOnFlockFeed(flock.Id),
                    PriceSpentOnMed = _flockService.GetAmountSpentOnFlockMed(flock.Id),
                    NoOfBirdsSold = _salesItemService.TotalNoOfBirdSoldPerFlock(flock.Id),
                    AmountPurchased = _salesItemService.AmountOfSalesPerFlock(flock.Id),
                };

                ListFlock.Add(listFlockVM);
            }

            User userlogin = _userService.FindById(userId);
            ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";
            int pageSize = 3;
            return View(PaginatedList<ListFlockVM>.CreateAsync(ListFlock.AsQueryable(), pageNumber ?? 1, pageSize));
        }

        [Authorize(Roles = "Super Admin, Admin")]
        public IActionResult Details(int id)
        {
            int userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
            User userlogin = _userService.FindById(userId);
            ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";

            var flock = _flockService.FindById(id);

Views/Flock/AddFlock.cshtml
@model NikeFarms.v2._0.Models.ViewModels.AddFlockVM

@{ ViewBag.Title = "Add Flocks"; }
@{
    Layout = "_StoreManagerDashboard";
}


<div class="container">
    <div class="">
        <div class="">
            <div class="">
                <div class="">
                    <br /><br /><h2 class="text-center font-weight-bolder" style="color:darkred"><i class="fab fa-twitter"></i> Add Flocks</h2><br /><br />
                </div>
                <form method="post">
                    <div class="">
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label asp-for="TotalNo" class="form-check-label font-weight-bold"><span style="color: darkred">*</span> Total Number of Incoming Flock </label>
                                <input style="margin-right: 20px" asp-for="TotalNo" class="form-control " placeholder="Input Total No." type="number" min="1" />
                                <span asp-validation-for="TotalNo" style="color:darkred"></span>
                            </div>
                            <div class="form-group col-md-2">
                            </div>
                            <div class="form-group col-md-5">
                                <label asp-for="Age" class="form-check-label font-weight-bold"><span style="color: darkred">*</span> Age of Incoming Flock (In Days)</label>
                                <input style="margin-right: 20px" asp-for="Age" class="form-control" placeholder="Enter Flock Age (In Days)" type="number" min="1"/>
                                <span asp-validation-for="Age" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label asp-for="AverageWeight" class="form-check-label font-weight-bold"><span style="color: darkred">*</span> Average Weight (Kg)</label>
                                <input asp-for="AverageWeight" class="form-control" placeholder="Enter Average Weight of Incoming Flock (Kg)" type="number" min="0.01"/>
                                <span asp-validation-for="AverageWeight" style="color:darkred"></span>
                            </div>
                            <div class="form-group col-md-2">
                            </div>
                            <div class="form-group col-md-5">
                                <label asp-for="AmountPurchased" class="form-check-label font-weight-bold"><span style="color: darkred">*</span> Price of Flock (&#8358 ) </label>
                                <input asp-for="AmountPurchased" class="form-control" placeholder="Total Amount used to Purchase Flock (N)" type="number" min="1"/>
                                <span asp-validation-for="AmountPurchased" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label class="form-check-label font-weight-bold" asp-for="FlockTypeId"><span style="color: darkred">*</span> Select Flock Type</label>
                                <select asp-for="FlockTypeId" asp-items="@Model.FlockTypeList" class="form-control">
                                    <option disabled selected>--Select Flock Type--</option>
                                </select>
                                <span asp-validation-for="FlockTypeId" style="color:darkred"></span><br>
                            </div>
                        </div>
                    </div>
                    <div class="">
                        <input type="submit" value="Add Flock" class="btn font-weight-bolder" style="background-color:darkgoldenrod" />
                        <a style="margin-left: 5%; color: darkred" asp-action="Index">Back Home</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Flock/Details.cshtml
@model NikeFarms.v2._0.Models.ViewModels.ListFlockVM
@{ ViewBag.Title = "Flocks"; }

@{

    Layout = "_AdminDashboard";

}


<h1 class="text-center" style="font-family:'Times New Roman'; color:darkred ">
    <i class="fab fa-twitter"></i> Flock @Model.FlockType (@Model.BatchNo) <button style="margin-left:20px" class="btn btn-outline-secondary" onclick="window.print()"><i class="fas fa-save"></i>  Save</button>
</h1>

<div>
    <br />
    <div class="" style="font-size: 20px">


        <span class="font-weight-bolder"><span style="color:darkred">*</span>Batch No: <span style="color:darkred">@Model.BatchNo</span></span><br /><br />

        <span class="font-weight-bolder"><span style="color:darkred">*</span>Flock Type: <span style="font-weight: lighter">@Model.FlockType</span></span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Amount(Purchased): &#8358 <span style="font-weight: lighter" class="comma">@Model.AmountPurchased</span> </span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Date(Intake): <span style="font-weight: lighter">@Model.CreatedAt.ToLongDateString()</span></span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Date(Now): <span style="font-weight: lighter">@DateTime.Now.ToLongDateString()</span></span><br /><br />
        <span class="font-weight-bolder">
            <span style="color:darkred;">*</span>Age: <span style="font-weight: lighter">

                @if (Model.currentAge < 31)
                {
                    @Model.currentAge <span class="font-weight-bolder">Day(s)</span><br />
                }
                else if (Model.currentAge > 30 && Model.currentAge < 356)
                {
                    int remainder = Model.currentAge % 31;
                    int month = Model.currentAge / 31;
                    if (remainder == 0)
                    {
                        @month <span class="font-weight-bolder">Month(s)</span><br />
                    }
                    else
                    {
                        @month <span class="font-weight-bolder">Month(s)</span> @remainder <span class="font-weight-bolder">Day(s)</span><br />
                    }

                }
                else
                {
                    if (Model.currentAge >= 365)
                    {
                        int rmonth = (Model.currentAge % 365) / 31;
                        int year = Model.currentAge / 365;
                        int rday = (Model.currentAge % 365) % 31;
                        if (rmonth == 0)
                        {
                            @year <span class="font-weight-bolder">Year(s)</span><br />
                        }
                        else if (rday == 0)
                        {
                            @year <span class="font-weight-bolder">Year(s)</span> @rmonth <span class="font-weight-bolder">Month(s)</span><br />
                        }
                        else
                        {
                            @year <span class="font-weight-bolder">Year(s)</span> @rmonth <span class="font-weight-bolder">Month(s)</span> @rday <span class="font-weight-bolder">Day(s)</span><br />
                        }

                    }

                }
            </span>
        </span><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Initially Stocked: <span style="font-weight: lighter" class="comma">@Model.TotalNo</span> Bird(s)</span><br /><br />
        @if (Model.AvailableBirds <= 10)
        {
            <span class="font-weight-bolder" style="color:red"><span style="color:darkred">*</span>Available Birds: <span class="comma">@Model.AvailableBirds</span> Bird(s)!!</span><br /><br />
        }
        else
        {
            <span class="font-weight-bolder"><span style="color:darkred">*</span>Available Birds: <span style="font-weight: lighter" class="comma">@Model.AvailableBirds</span> Bird(s)</span><br /><br />
        }

        <span class="font-weight-bolder"><span style="color:darkred">*</span>Mortality: <span style="font-weight: lighter" class="comma">@Model.Mortality</span> Death(s)</span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>No Sold: <span style="font-weight: lighter" class="comma">@Model.NoOfBirdsSold</span> Bird(s)</span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Average Weight(Initial): <span style="font-weight: lighter" class="comma">@Model.InitialAverageWeight</span> Kg</span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Average Weight(Now): <span style="font-weight: lighter" class="comma">@Model.CurrentAverageWeight</span> Kg</span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Total Weight(Feed Consumed): <span style="font-weight: lighter" class="comma">@Model.TotalKgOfFeedConsumed</span> Kg</span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Expenses(Feed): &#8358 <span style="font-weight: lighter" class="comma">@Model.PriceSpentOnFeed</span></span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Expenses(Med): &#8358 <span style="font-weight: lighter" class="comma">@Model.PriceSpentOnMed</span> </span><br /><br />
        <span class="font-weight-bolder"><span style="color:darkred">*</span>Amount(Sales): &#8358 <span style="font-weight: lighter" class="comma">@Model.TotalSalesPrice</span> </span><br /><br />
    </div>

</div>


<script>

    function numberWithCommas(x) {
        let newNumber = x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");
        return newNumber
    }


    let comma = document.getElementsByClassName("comma");


    for (var i = 0; i < comma.length; i++) {
        let result = numberWithCommas(comma[i].innerHTML);
        document.getElementsByClassName("comma")[i].innerHTML = result;
    }

    
</script>

Views/Flock/Index.cshtml
@model PaginatedList<NikeFarms.v2._0.Models.ViewModels.ListFlockVM>
@{ ViewBag.Title = "Flocks"; }
@{
    Layout = "_StoreManagerDashboard";
}
<br />
<h1 class="text-center"><i class="fab fa-twitter"></i>  Flocks</h1>

<div class="card">
    <div>
        <br />
        <form asp-action="Index" method="get" style="margin-left:70%">

            <input class="form-control col-md-10" style="margin-bottom:5%" type="search" placeholder="Search (Batch No/ Flock Type)..." name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-outline-secondary" /> |
            <a style="color:darkred" asp-action="Index">Back to Full List</a>

        </form>
        <a class="btn font-weight-bold ml-4" asp-controller="Flock" asp-action="AddFlock" style="background-color:darkgoldenrod"><i class="fas fa-plus"></i> Add Flocks</a>

        @if (Model.Count() > 0)
        {
            <div class="card-body">
                <table class="table table-bordered ">
                    <thead>
                        <tr>

                            <th> Batch No.</th>
                            <th> Flock Type </th>
                            <th> Current Age </th>
                            <th> Current Weight (KG)</th>
                            <th> Available Bird(s) </th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var flock in Model)
                        {
                            string modalId = $"exampleModalCenter{flock.Id}";
                            string modalIdHash = $"#exampleModalCenter{flock.Id}";
                            <tr>

                                <td class="font-weight-bolder">
                                    <span style="color:darkred">*</span> @flock.BatchNo @if (flock.IsApproved == true)
                                    {<span><a class="btn font-weight-bold" style=" color: greenyellow;" href="#"><i class="fas fa-check"></i></a></span>}
                                </td>
                                <td>@flock.FlockType</td>
                                @if (flock.currentAge < 31)
                                {
                                    <td>@flock.currentAge <span class="font-weight-bolder">Day(s)</span></td>
                                }
                                else if (flock.currentAge > 30 && flock.currentAge < 356)
                                {
                                    int remainder = flock.currentAge % 31;
                                    int month = flock.currentAge / 31;
                                    if (remainder == 0)
                                    {
                                        <td>@month <span class="font-weight-bolder">Month(s)</span> </td>
                                    }
                                    else
                                    {
                                        <td>@month <span class="font-weight-bolder">Month(s)</span> @remainder <span class="font-weight-bolder">Day(s)</span></td>
                                    }

                                }
                                else
                                {
                                    if (flock.currentAge >= 365)
                                    {
                                        int rmonth = (flock.currentAge % 365) / 31;
                                        int year = flock.currentAge / 365;
                                        int rday = (flock.currentAge % 365) % 31;
                                        if (rmonth == 0)
                                        {
                                            <td>@year <span class="font-weight-bolder">Year(s)</span></td>
                                        }
                                        else if (rday == 0)
                                        {
                                            <td>@year <span class="font-weight-bolder">Year(s)</span> @rmonth <span class="font-weight-bolder">Month(s)</span></td>
                                        }
                                        else
                                        {
                                            <td>@year <span class="font-weight-bolder">Year(s)</span> @rmonth <span class="font-weight-bolder">Month(s)</span> @rday <span class="font-weight-bolder">Day(s)</span></td>
                                        }

                                    }

                                }

                                <td><span class="comma">@flock.CurrentAverageWeight</span> <span class="font-weight-bolder">Kg</span></td>
                                @if (flock.AvailableBirds < 11)
                                {
                                    <td style="color:red"><span class="comma">@flock.AvailableBirds</span> <span class="font-weight-bolder">Bird(s) !!</span></td>
                                }
                                else
                                {
                                    <td><span class="comma">@flock.AvailableBirds</span> <span class="font-weight-bolder">Bird(s)</span></td>
                                }


                                @if (flock.IsApproved == false && flock.CreatedBy == ViewBag.UserName)
                                {
                                    <td>
                                        <a class="btn font-weight-bold" asp-action="UpdateFlock" asp-route-id="@flock.Id" style="background-color:greenyellow; color:white">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a class="btn font-weight-bold" style="background-color:red; color:white" data-toggle="modal" data-target=@modalIdHash>
                                            <i class="fas fa-trash-alt"></i>
                                        </a>


                                        <div class="modal fade" id=@modalId tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title font-weight-bolder" style="color:red" id="exampleModalLongTitle">Delete Flock <i class="fas fa-trash-alt"></i> </h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <br /> <span class="font-weight-bolder text-center">Are you Sure you want to delete Flock with Batch No: <span style="color:darkred">@flock.BatchNo (@flock.FlockType) ??</span></span>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <a class="btn font-weight-bold" style="background-color:red; color:white" asp-action="Delete" asp-route-id="@flock.Id">Yes</a>
                                                        <a class="btn font-weight-bold" style="background-color:greenyellow; color:white" data-dismiss="modal">No</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                }



                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <br /><br />
            <h4 class="text-center font-weight-bolder" style="color:red">No Flock Found! </h4>
        }
    </div>
</div>


<script>
    //$('#example').dataTable({
    //});

    function numberWithCommas(x) {
        let newNumber = x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");
        return newNumber
    }


    let comma = document.getElementsByClassName("comma");


    for (var i = 0; i < comma.length; i++) {
        let result = numberWithCommas(comma[i].innerHTML);
        document.getElementsByClassName("comma")[i].innerHTML = result;
    }


</script>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-default @nextDisabled">
    Next
</a>