Models/DailyActivity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NikeFarms.v2._0.Models
{
    public class DailyActivity : BaseEntity
    {

        public double NoOfMedUsed { get; set; }

        public double NoOfFeedUsed { get; set; }

        public Flock Flock { get; set; }

        public int FlockId { get; set; }

        public StoreAllocation StoreAllocationFeed { get; set; }

        public int StoreAllocationFeedId { get; set; }

        public StoreAllocation StoreAllocationMed { get; set; }

        public int? StoreAllocationMedId { get; set; }

        public string Date { get; set; }

    }
}

Controllers/DailyActivityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NikeFarms.v2._0.Interface;
using NikeFarms.v2._0.Models;
using NikeFarms.v2._0.Models.DTO;
using NikeFarms.v2._0.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NikeFarms.v2._0.Controllers
{
   
    public class DailyActivityController : Controller
    {
        private readonly IUserService _userService;
        private readonly IFlockService _flockService;
        private readonly IFlockTypeService _flockTypeService;
        private readonly IDailyActivityService _dailyService;
        private readonly IStoreAllocationService _storeAllocationService;
        private readonly IStoreItemService _storeItemService;

        public DailyActivityController(IStoreAllocationService storeAllocationService, IUserService userService, IFlockService flockService, IDailyActivityService dailyService, IFlockTypeService flockTypeService, IStoreItemService storeItemService)
        {
            _storeAllocationService = storeAllocationService;
            _userService = userService;
            _flockService = flockService;
            _dailyService = dailyService;
            _flockTypeService = flockTypeService;
            _storeItemService = storeItemService;
        }

        [Authorize(Roles = "Super Admin, Farm Manager")]
        public IActionResult Index(string sortOrder, string searchString, int? pageNumber)
        {
            var dailyActs = _dailyService.GetAllDailyActivities();
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                dailyActs = dailyActs.Where(s => s.Flock.BatchNo.Contains(searchString));
            }

            List<ListDailyActivityVM> ListDailyActivity = new List<ListDailyActivityVM>();
            foreach (var dailyAct in dailyActs)
            {
                var Created = _userService.FindByEmail(dailyAct.CreatedBy);
                var Flock = _flockService.FindById(dailyAct.FlockId);
                var storeAllocationMed = _storeAllocationService.FindMedById(dailyAct.StoreAllocationMedId);
                var storeAllocationFeed = _storeAllocationService.FindById(dailyAct.StoreAllocationFeedId);

                string MedName = "null";
                if (storeAllocationMed != null)
                {
                    MedName = _storeItemService.FindById(storeAllocationMed.StoreItemId).Name;
                };

                ListDailyActivityVM listDailyActivityVM = new ListDailyActivityVM
                {
                    Id = dailyAct.Id,
                    FlockDescription = $"{_flockTypeService.FindById(Flock.FlockTypeId).Name}  Batch No: {Flock.BatchNo}",
                    MedUsed = MedName,
                    NoOfMedUsed = dailyAct.NoOfMedUsed,
                    FeedUsed = $"{_storeItemService.FindById(storeAllocationFeed.StoreItemId).Name}",
                    NoOfFeedUsed = dailyAct.NoOfFeedUsed,
                    CreatedAt = dailyAct.Date,
                    CreatedBy = $"{Created.FirstName} .{Created.LastName[0]}",
                };

                ListDailyActivity.Add(listDailyActivityVM);
            }

            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            User userlogin = _userService.FindById(userId);
            ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";
            int pageSize = 5;
            return View(PaginatedList<ListDailyActivityVM>.CreateAsync(ListDailyActivity.AsQueryable(), pageNumber ?? 1, pageSize));
        }

        [Authorize(Roles = "Super Admin, Farm Manager")]
        public IActionResult AddDailyActivity()
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            User userlogin = _userService.FindById(userId);
            ViewBag.UserName = $"{userlogin.FirstName} .{userlogin.LastName[0]}";

            AddDailyActivityVM dailyActivityVM = new AddDailyActivityVM
            {

                FlockList = _flockService.OperationDaily().Select(f => new SelectListItem
                {
                    Text = $"{_flockTypeService.FindById(f.FlockTypeId).Name} Batch No: ({_flockService.FindById(f.Id).BatchNo}) Available: {_flockService.FindById(f.Id).AvailableBirds} Bird(s)",
                    Value = f.Id.ToString()
                }),

                FeedAllocationList = _storeAllocationService.FeedAllocation(userId).Select(f => new SelectListItem
                {
                    Text = $"{_storeItemService.FindById(f.StoreItemId).Name} ({_storeAllocationService.FindById(f.Id).ItemRemaining})",
                    Value = f.Id.ToString()
                }),

                MedAllocationList = _storeAllocationService.MedAllocation(userId).Select(f => new SelectListItem
                {
                    Text = $"{_storeItemService.FindById(f.StoreItemId).Name} ({_storeAllocationService.FindById(f.Id).ItemRemaining})",
                    Value = f.Id.ToString()
                }),
            };
            return View(dailyActivityVM);
        }

        [HttpPost]
        public IActionResult AddDailyActivity(AddDailyActivityVM addDailyActivity)
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            DailyActivityDTO dailyActivityDTO = new DailyActivityDTO
            {
                UserId = userId,
                NoOfMedUsed = addDailyActivity.NoOfMedUsed,
                NoOfFeedUsed = addDailyActivity.NoOfFeedUsed,
                FlockId = addDailyActivity.FlockId,
                StoreAllocationFeedId = addDailyActivity.StoreAllocationFeedId,
                StoreAllocationMedId = addDailyActivity.StoreAllocationMedId,
            };

            double StoreAlloFeedRemaining = _storeAllocationService.FindById(addDailyActivity.StoreAllocationFeedId).ItemRemaining;
            int availableBirds = _flockService.FindById(addDailyActivity.FlockId).AvailableBirds;
            double? StoreAlloMedRemaining = 0;
            if (_storeAllocationService.FindMedById(addDailyActivity.StoreAllocationMedId) != null)
            {
                StoreAlloMedRemaining = _storeAllocationService.FindMedById(addDailyActivity.StoreAllocationMedId).ItemRemaining;
            }

            if (StoreAlloFeedRemaining < addDailyActivity.NoOfFeedUsed || StoreAlloMedRemaining < addDailyActivity.NoOfMedUsed)
            {
                if (StoreAlloFeedRemaining < addDailyActivity.NoOfFeedUsed)
                {
                    ViewBag.Message = "errorFeed";
                }
                else if (StoreAlloMedRemaining < addDailyActivity.NoOfMedUsed)
                {
                    ViewBag.Message = "errorMed";
                }
               

                AddDailyActivityVM dailyActivityVM = new AddDailyActivityVM
                {

                    FlockList = _flockService.OperationDaily().Select(f => new SelectListItem
                    {
                        Text = $"{_flockTypeService.FindById(f.FlockTypeId).Name} Batch No: ({_flockService.FindById(f.Id).BatchNo}) Available: {_flockService.FindById(f.Id).AvailableBirds} Bird(s)",
                        Value = f.Id.ToString()
                    }),

                    FeedAllocationList = _storeAllocationService.FeedAllocation(userId).Select(f => new SelectListItem
                    {
                        Text = $"{_storeItemService.FindById(f.StoreItemId).Name} ({_storeAllocationService.FindById(f.Id).ItemRemaining})",
                        Value = f.Id.ToString()
                    }),

                    MedAllocationList = _storeAllocationService.MedAllocation(userId).Select(f => new SelectListItem
                    {
                        Text = $"{_storeItemService.FindById(f.StoreItemId).Name} ({_storeAllocationService.FindById(f.Id).ItemRemaining})",
                        Value = f.Id.ToString()
                    }),
                };
                return View(dailyActivityVM);
            };



            var feedAllo = _storeAllocationService.FindById(addDailyActivity.StoreAllocationFeedId);
            if (feedAllo != null)
            {
                StoreAllocationDTO feedStoreAllocation = new StoreAllocationDTO
                {
                    Id = feedAllo.Id,
                    UserId = userId,
                    StoreItemId = feedAllo.StoreItemId,
                    ManagerId = feedAllo.ManagerId,
                    NoOfItem = feedAllo.NoOfItem,
                    ItemRemaining = feedAllo.ItemRemaining - addDailyActivity.NoOfFeedUsed,
                    IsApproved = true,
                };
                _storeAllocationService.Update(feedStoreAllocation);

            };


            var medAllo = _storeAllocationService.FindMedById(addDailyActivity.StoreAllocationMedId);
            if (medAllo != null)
            {
                StoreAllocationDTO medStoreAllocation = new StoreAllocationDTO
                {
                    Id = medAllo.Id,
                    UserId = userId,
                    StoreItemId = medAllo.StoreItemId,
                    ManagerId = medAllo.ManagerId,
                    NoOfItem = medAllo.NoOfItem,
                    ItemRemaining = medAllo.ItemRemaining - addDailyActivity.NoOfMedUsed,
                    IsApproved = true,
                };
                _storeAllocationService.Update(medStoreAllocation);
            };

        
            _dailyService.Add(dailyActivityDTO);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Super Admin, Admin")]
        public IActionResult ListDailyActivity(int id, string sortOrder, int? pageNumber)
        {

Views/DailyActivity/AddDailyActivity.cshtml
@model NikeFarms.v2._0.Models.ViewModels.AddDailyActivityVM

@{ ViewBag.Title = "Add Daily Activity"; }
@{
    Layout = "_FarmManagerDashboard";
}


<div class="container">
    <div class="">
        <div class="">
            <div class="">
                <div class="">
                    <br /><br /><h3 class="text-center font-weight-bolder" style="color:darkred"><i class="fas fa-calendar-day"></i>  Add Today's Activity (@DateTime.Now.ToLongDateString())</h3><br /><br />
                </div>
                @if (ViewBag.Message == "errorFeed")
                {
                    <p style="color:red; " class="text-center font-weight-bolder  mb-2">*The No. of Feed you Input is more than what has been Allocated to you</p>
                }
                else if (ViewBag.Message == "errorMed")
                {
                    <p style="color:red; " class="text-center font-weight-bolder  mb-2">*The No. of Medicine you Input is more than what has been Allocated to you</p>
                }
                <form method="post">
                    <div class="">
                        <div class="form-row">

                            <div class="form-group col-md-5">
                                <label class="form-check-label font-weight-bold" asp-for="FlockId"><span style="color: darkred">*</span> Select Flock</label>
                                <select asp-for="FlockId" asp-items="@Model.FlockList" class="form-control">
                                    <option disabled selected>--Select Flock --</option>
                                </select>
                                <span asp-validation-for="FlockId" style="color:darkred"></span><br>
                            </div>
                            <div class="form-group col-md-2">
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label class="form-check-label font-weight-bold" asp-for="StoreAllocationFeedId"><span style="color: darkred">*</span> Select Feed</label>
                                <select asp-for="StoreAllocationFeedId" asp-items="@Model.FeedAllocationList" class="form-control">
                                    <option disabled selected>--Select Feed Consumed --</option>
                                </select>
                                <span asp-validation-for="StoreAllocationFeedId" style="color:darkred"></span><br>
                            </div>
                            <div class="form-group col-md-2">
                            </div>
                            <div class="form-group col-md-5">
                                <label asp-for="NoOfFeedUsed" class="form-check-label font-weight-bold"><span style="color: darkred">*</span> Number of Feed Consumed </label>
                                <input asp-for="NoOfFeedUsed" class="form-control" placeholder="Total No. of Feed Consumed" type="number" min="1" />
                                <span asp-validation-for="NoOfFeedUsed" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label class="form-check-label font-weight-bold" asp-for="StoreAllocationMedId"><span style="color: darkred"></span> Select Medication</label>
                                <select asp-for="StoreAllocationMedId" asp-items="@Model.MedAllocationList" class="form-control">
                                    <option disabled selected>--Select Medication Used --</option>
                                </select>
                                <span asp-validation-for="StoreAllocationMedId" style="color:darkred"></span><br>
                            </div>
                            <div class="form-group col-md-2">
                            </div>
                            <div class="form-group col-md-5">
                                <label asp-for="NoOfMedUsed" class="form-check-label font-weight-bold"><span style="color: darkred">*</span> Number of Med Used </label>
                                <input asp-for="NoOfMedUsed" class="form-control" placeholder="Total No. of Medication Used" type="number" min="0" />
                                <span asp-validation-for="NoOfMedUsed" style="color:darkred"></span>
                            </div>
                        </div>
                    </div>
                    <div class="">
                        <input type="submit" value="Add Record" class="btn font-weight-bolder" style="background-color:darkgoldenrod" />
                        <a style="margin-left: 5%; color: darkred" asp-action="Index">Back Home</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DailyActivity/Index.cshtml
@model PaginatedList<NikeFarms.v2._0.Models.ViewModels.ListDailyActivityVM>
@{ ViewBag.Title = "Daily Activity"; }

@{
    Layout = "_FarmManagerDashboard";

}

<br />
<h1 class="text-center" style="color:darkred"><i class="fas fa-calendar-day"></i>  Daily Activities </h1>
<br />
<div class="card">
    <div>
        <br />
        <form asp-action="Index" method="get" style="margin-left:70%">

            <input class="form-control col-md-10" style="margin-bottom:5%" type="search" placeholder="Search (Batch No)..." name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-outline-secondary" /> |
            <a style="color:darkred" asp-action="Index">Back to Full List</a>

        </form>
        <a class="btn font-weight-bold ml-4" asp-controller="DailyActivity" asp-action="AddDailyActivity" style="background-color:darkgoldenrod"><i class="fas fa-plus"></i> Add Today's Activity</a>

        @if (Model.Count() > 0)
        {
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th> Flock</th>
                            <th> Feed Type</th>
                            <th> Feed Consumed </th>
                            <th> Medication</th>
                            <th> No. of Med Used</th>
                            <th>Date</th>
                            <th> Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var daily in Model)
                        {
                            string modalId = $"exampleModalCenter{daily.Id}";
                            string modalIdHash = $"#exampleModalCenter{daily.Id}";
                            <tr>
                                <td>@daily.FlockDescription</td>
                                <td class="font-weight-bolder"><span style="color:darkred">*</span> @daily.FeedUsed</td>
                                <td><span class="comma">@daily.NoOfFeedUsed</span> Bag(s)</td>
                                @if (daily.MedUsed == "null")
                                {
                                    <td class="font-weight-bold" style="color:red">Null</td>
                                }
                                else
                                {
                                    <td class="font-weight-bolder"><span style="color:darkred">*</span> @daily.MedUsed </td>
                                }
                                @if (daily.NoOfMedUsed <= 0)
                                {
                                    <td class="font-weight-bold" style="color:red">Null</td>
                                }
                                else
                                {
                                    <td><span class="comma">@daily.NoOfMedUsed</span> Unit(s)</td>
                                }

                                <td class="font-weight-bolder">@daily.CreatedAt</td>

                                @if (daily.CreatedAt == DateTime.Now.ToShortDateString() && daily.CreatedBy == ViewBag.UserName)
                                {
                                    <td>
                                        <a class="btn font-weight-bold" style="background-color:red; color:white" data-toggle="modal" data-target=@modalIdHash>
                                            <i class="fas fa-trash-alt"></i>
                                        </a>


                                        <div class="modal fade" id=@modalId tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title font-weight-bolder" style="color:red" id="exampleModalLongTitle">Delete Flock <i class="fas fa-trash-alt"></i> </h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <br /> <span class="font-weight-bolder text-center">Are you Sure you want to delete Today's Activity For  <span style="color:darkred">@daily.FlockDescription ??</span></span>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <a class="btn font-weight-bold" style="background-color:red; color:white" asp-action="Delete" asp-route-id="@daily.Id">Yes</a>
                                                        <a class="btn font-weight-bold" style="background-color:greenyellow; color:white" data-dismiss="modal">No</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </td>

                                }

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <br /><br />
            <h4 class="text-center font-weight-bolder" style="color:darkred">No Daily Activity has been Added !! </h4>
        }
    </div>
</div>


<script>

    function numberWithCommas(x) {
        let newNumber = x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");
        return newNumber
    }


    let comma = document.getElementsByClassName("comma");


    for (var i = 0; i < comma.length; i++) {
        let result = numberWithCommas(comma[i].innerHTML);
        document.getElementsByClassName("comma")[i].innerHTML = result;
    }


</script>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-default @nextDisabled">
    Next
</a>

Views/DailyActivity/ListDailyActivity.cshtml
@model PaginatedList<NikeFarms.v2._0.Models.ViewModels.ListDailyActivityVM>
@{ ViewBag.Title = "Daily Activity"; }

@{
    Layout = "_AdminDashboard";

}

<br />
<h3 class="text-center" style="color:darkred"><i class="fas fa-calendar-day"></i>  Daily Activities (@ViewBag.FlockD)</h3>
<br />
<div class="card">
    <div>
        <br />
        @if (Model.Count() > 0)
        {
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>

                            <th> Feed Type</th>
                            <th> Feed Consumed </th>
                            <th> Medication</th>
                            <th> No. of Med Used</th>
                            <th> Date</th>
                            <th> Created By</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var daily in Model)
                        {
                            <tr>

                                <td class="font-weight-bolder"><span style="color:darkred">*</span> @daily.FeedUsed</td>
                                <td><span class="comma">@daily.NoOfFeedUsed</span> Bag(s)</td>
                                @if (daily.MedUsed == "null")
                                {
                                    <td class="font-weight-bold" style="color:red">Null</td>
                                }
                                else
                                {
                                    <td class="font-weight-bolder"><span style="color:darkred">*</span> @daily.MedUsed </td>
                                }
                                @if (daily.NoOfMedUsed <= 0)
                                {
                                    <td class="font-weight-bold" style="color:red">Null</td>
                                }
                                else
                                {
                                    <td><span class="comma">@daily.NoOfMedUsed</span> Unit(s) </td>
                                }

                                <td class="font-weight-bolder">@daily.CreatedAt</td>
                                <td>@daily.CreatedBy (Farm Manager)</td>


                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <br /><br />
            <h4 class="text-center font-weight-bolder" style="color:darkred">No Daily Activity has been Added for this Flock! </h4>
        }
    </div>
</div>


<script>

    function numberWithCommas(x) {
        let newNumber = x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");
        return newNumber
    }


    let comma = document.getElementsByClassName("comma");


    for (var i = 0; i < comma.length; i++) {
        let result = numberWithCommas(comma[i].innerHTML);
        document.getElementsByClassName("comma")[i].innerHTML = result;
    }


</script>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="ListDailyActivity"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="ListDailyActivity"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-default @nextDisabled">
    Next
</a>